services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./plots:/app/plots
      - ./logs:/app/logs
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - redis
      - ollama

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  redis_data:
  ollama_data: